// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/one/structure.proto

package one

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccc3687bb8981fb1, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "grpctest.proto.one.SearchRequest")
}

func init() { proto.RegisterFile("proto/one/structure.proto", fileDescriptor_ccc3687bb8981fb1) }

var fileDescriptor_ccc3687bb8981fb1 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x8b, 0x0b, 0x55, 0x31, 0x05, 0xd1, 0xc1, 0x9d, 0x6a, 0x3a, 0x18, 0x2f, 0xb1,
	0x20, 0x7e, 0x83, 0x3c, 0x40, 0x62, 0x9c, 0x2d, 0x8b, 0x91, 0xc5, 0x21, 0x07, 0x6c, 0x49, 0x3e,
	0x9d, 0x86, 0xbc, 0x7d, 0x90, 0x0c, 0xd9, 0xee, 0xfb, 0xee, 0x1f, 0x3e, 0xf6, 0xeb, 0xd0, 0x92,
	0x15, 0xd6, 0x80, 0xf0, 0x84, 0x41, 0x51, 0x40, 0x68, 0x93, 0xe3, 0x5c, 0xa3, 0x53, 0x04, 0x9e,
	0x76, 0x6e, 0xad, 0x81, 0x7f, 0xc3, 0x8a, 0x2b, 0x48, 0x54, 0xf3, 0x00, 0x5b, 0x00, 0x4f, 0xfc,
	0x87, 0xe5, 0x5b, 0x00, 0x7c, 0x94, 0x59, 0x95, 0x35, 0x9f, 0xc3, 0x0e, 0xfc, 0x8f, 0x7d, 0x39,
	0xa9, 0x61, 0x34, 0x61, 0x9d, 0x00, 0xcb, 0xb7, 0x2a, 0x6b, 0xf2, 0x81, 0x45, 0x75, 0x4e, 0x86,
	0xd7, 0xec, 0x1b, 0xc1, 0x87, 0x85, 0x46, 0x07, 0x38, 0xc6, 0x47, 0xf9, 0x9e, 0x46, 0xc5, 0xae,
	0x7b, 0xc0, 0x5e, 0x6a, 0x38, 0x35, 0xb7, 0x5a, 0xdf, 0x69, 0x0e, 0x53, 0xab, 0xec, 0x2a, 0x2e,
	0x0b, 0x18, 0x79, 0xec, 0x44, 0x0c, 0x3b, 0xc4, 0x32, 0xf1, 0xaa, 0x9f, 0x3e, 0xd2, 0xd9, 0x3d,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x88, 0xc6, 0x01, 0xc4, 0xd1, 0x00, 0x00, 0x00,
}
